### ISSUE TITLE
NPE with empty source dir

### ISSUE THREAD

**Issue by jorgefranconunes** [jorgefranconunes/yawg#128]
See below how to reproduce the problem.

```
./bin/yawg --assets ./doc/assets/ --source= --target=../yawg.gh-pages/ --templates ./doc/templates/ --verbose
2016-07.13 09:21:29.397 INFO Yawg 0.9.0-SNAPSHOT
2016-07.13 09:21:29.397 INFO     Source    : 
2016-07.13 09:21:29.397 INFO     Target    : ..\yawg.gh-pages
2016-07.13 09:21:29.397 INFO     Templates : .\doc\templates
2016-07.13 09:21:29.397 INFO     Assets    : .\doc\assets
2016-07.13 09:21:29.397 INFO Starting bake...
2016-07.13 09:21:29.397 INFO Starting copying assets...
2016-07.13 09:21:29.428 INFO Done copying assets (delay 31ms)
2016-07.13 09:21:29.428 INFO Starting baking source tree...
2016-07.13 09:21:29.428 FINE Baking directory 
2016-07.13 09:21:29.569 FINE     ..\.gitignore with copy (0ms)
2016-07.13 09:21:29.585 FINE     ..\.travis.yml with copy (16ms)
2016-07.13 09:21:29.600 FINE     ..\00README-developers.txt with copy (15ms)
2016-07.13 09:21:29.600 FINE     ..\00README.txt with copy (0ms)
2016-07.13 09:21:29.616 FINE     ..\COPYING.txt with copy (16ms)
2016-07.13 09:21:29.631 FINE     ..\LICENSE.txt with copy (15ms)
2016-07.13 09:21:29.631 WARNING Failed baking source tree - NullPointerException - null
2016-07.13 09:21:29.631 WARNING Failed bake - NullPointerException - null
Exception in thread "main" java.lang.NullPointerException
        at com.varmateo.yawg.asciidoctor.AsciidoctorBakerDataModelBuilder.build(AsciidoctorBakerDataModelBuilder.java:62)
        at com.varmateo.yawg.asciidoctor.AsciidoctorBaker.doBakeWithTemplate(AsciidoctorBaker.java:206)
        at com.varmateo.yawg.asciidoctor.AsciidoctorBaker.doBake(AsciidoctorBaker.java:148)
        at com.varmateo.yawg.asciidoctor.AsciidoctorBaker.bake(AsciidoctorBaker.java:122)
        at com.varmateo.yawg.FileBaker.bakeFile(FileBaker.java:73)
        at com.varmateo.yawg.DirBaker.bakeChildFiles(DirBaker.java:164)
        at com.varmateo.yawg.DirBaker.bakeDirectory(DirBaker.java:105)
        at com.varmateo.yawg.SingleSiteBaker.bakeSourceTree(SingleSiteBaker.java:113)
        at com.varmateo.yawg.SingleSiteBaker$$Lambda$25/168398198.run(Unknown Source)
        at com.varmateo.yawg.logging.LogWithUtils.lambda$logDelay$14(LogWithUtils.java:63)
        at com.varmateo.yawg.logging.LogWithUtils$$Lambda$23/83534488.get(Unknown Source)
        at com.varmateo.yawg.logging.LogWithUtils.performAction(LogWithUtils.java:110)
        at com.varmateo.yawg.logging.LogWithUtils.logDelay(LogWithUtils.java:91)
        at com.varmateo.yawg.logging.LogWithUtils.logDelay(LogWithUtils.java:66)
        at com.varmateo.yawg.SingleSiteBaker.doBake(SingleSiteBaker.java:96)
        at com.varmateo.yawg.SingleSiteBaker$$Lambda$22/358847552.run(Unknown Source)
        at com.varmateo.yawg.logging.LogWithUtils.lambda$logDelay$14(LogWithUtils.java:63)
        at com.varmateo.yawg.logging.LogWithUtils$$Lambda$23/83534488.get(Unknown Source)
        at com.varmateo.yawg.logging.LogWithUtils.performAction(LogWithUtils.java:110)
        at com.varmateo.yawg.logging.LogWithUtils.logDelay(LogWithUtils.java:91)
        at com.varmateo.yawg.logging.LogWithUtils.logDelay(LogWithUtils.java:66)
        at com.varmateo.yawg.SingleSiteBaker.bake(SingleSiteBaker.java:80)
        at com.varmateo.yawg.SiteBakerFactory$SiteBakerImpl.bake(SiteBakerFactory.java:68)
        at com.varmateo.yawg.cli.BakerCli.doBake(BakerCli.java:160)
        at com.varmateo.yawg.cli.BakerCli.doEverything(BakerCli.java:128)
        at com.varmateo.yawg.cli.BakerCli.main(BakerCli.java:73)
        at com.varmateo.yawg.cli.Main.main(Main.java:43)
```

**Comment by jorgefranconunes** [comment]
This problem is no longer reproducible.
