### ISSUE TITLE
build-create-bundle fails when JAVA_HOME not set

### ISSUE THREAD

**Issue by jorgefranconunes** [jorgefranconunes/yawg#304]
In the example below:

* JAVA_HOME is not set.
* There is a `java` command in the `PATH` belonging to OpenJDK 6.

```
2017-07-18 09:59:11.647 Yawg 0.9.6-SNAPSHOT - Release builder
2017-07-18 09:59:11.650     JDK           : /home/jfn/local/jdk1.8.0_74
2017-07-18 09:59:11.652     Maven         : /home/jfn/local/apache-maven-3.3.3/bin/mvn
2017-07-18 09:59:11.655     Maven options :  -DskipTests=false -Pyawg-jacoco -Dyawg.mavensite=/var/lib/jenkins/workspace/yawg/target/CodeQualityReports -DskipTests=false -Pyawg-mavensite
2017-07-18 09:59:11.657     Maven goals   : clean verify site
2017-07-18 09:59:11.660     Build number  : AUTOMATIC
2017-07-18 09:59:11.662 Maven details:
which: no javac in (/sbin:/usr/sbin:/bin:/usr/bin)
Warning: JAVA_HOME environment variable is not set.
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/cli/MavenCli : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.codehaus.plexus.classworlds.launcher.Launcher.getMainClass(Launcher.java:144)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:266)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
ERROR Failed to obtain Maven details
```

**Comment by jorgefranconunes** [comment]
Done.
